type Query {
  organization(login: ID!): Organization
  profile(login: ID!): ProfileOwner
  user(login: ID!): User
  node(id: ID!): Node
}

type Organization implements Node & ProfileOwner & RepositoryOwner {
  avatarUrl: String!
  description: String
  email: String
  followers(after: String, before: String, first: Int, last: Int): UserConnection!
  id: ID!
  location: String
  login: ID!
  name: String
  people(after: String, before: String, first: Int, last: Int): UserConnection!
  repositories(after: String, before: String, first: Int, last: Int): RepositoryConnection!
  url: String!
  websiteUrl: String
}

interface Node {
  id: ID!
}

interface ProfileOwner {
  avatarUrl: String!
  login: ID!
  name: String
  location: String
  url: String!
}

interface RepositoryOwner implements ProfileOwner {
  avatarUrl: String!
  login: ID!
  name: String
  location: String
  repositories(after: String, before: String, first: Int, last: Int): RepositoryConnection!
  url: String!
}

type RepositoryConnection {
  edges: [RepositoryEdge]!
  pageInfo: PageInfo!
}

type RepositoryEdge {
  cursor: String!
  node: Repository
}

type Repository implements Node {
  description: String
  forkCount: Int
  starCount: Int
  id: ID!
  licenseInfo: License
  name: String!
  owner: RepositoryOwner!
  primaryLanguage: Language
  url: String!
}

type License {
  name: String!
}

type Language {
  color: String!
  name: String!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

type UserConnection {
  edges: [UserEdge]!
  pageInfo: PageInfo!
}

type UserEdge {
  cursor: String!
  node: User
}

type User implements Node & ProfileOwner & RepositoryOwner {
  avatarUrl: String!
  bio: String
  company: String
  email: String!
  followers(after: String, before: String, first: Int, last: Int): UserConnection!
  following(after: String, before: String, first: Int, last: Int): FollowingConnection!
  id: ID!
  location: String
  login: ID!
  name: String
  organizations(after: String, before: String, first: Int, last: Int): OrganizationConnection!
  repositories(after: String, before: String, first: Int, last: Int): RepositoryConnection!
  starredRepositories(after: String, before: String, first: Int, last: Int): RepositoryConnection!
  url: String!
  websiteUrl: String
}

type FollowingConnection {
  edges: [FollowingEdge]!
  pageInfo: PageInfo!
}

type FollowingEdge {
  cursor: String!
  node: Following
}

type Following implements ProfileOwner {
  avatarUrl: String!
  followingAt: String
  login: ID!
  name: String
  location: String
  url: String!
}

type OrganizationConnection {
  edges: [OrganizationEdge]!
  pageInfo: PageInfo!
}

type OrganizationEdge {
  cursor: String!
  node: Organization
}